# Copyright (c) 2026 Said Borna. All rights reserved.
# Proprietary — see LICENSE for terms.
"""AI Model Attribution — identify which LLM generated code.

Three-tier attribution with decreasing confidence:
1. IDE hook data (0.95) — observed API calls
2. Git trailers (0.6-0.9) — commit metadata patterns
3. Code heuristics (0.25-0.9) — content pattern matching

Privacy: never reads or stores file content beyond pattern matching.
"""

from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path  # noqa: TC003 — used at runtime

import structlog

logger = structlog.get_logger()

# ─────────────────────────────────────────────────────────────────
#  Types
# ─────────────────────────────────────────────────────────────────

IDE_HOOK_CONFIDENCE = 0.95
MAX_IDE_HOOK_EVENTS = 500  # Max events to scan per file


@dataclass(frozen=True)
class AttributionSignal:
    """A signal indicating AI involvement."""

    source: str         # "openai", "anthropic", "github_copilot", "generic_ai", "human"
    model: str          # "gpt-4o", "claude-sonnet-4-20250514", "unknown"
    confidence: float   # 0.0-1.0
    evidence: str       # What triggered the detection
    method: str         # "ide_hook", "git_trailer", "heuristic"
    line: int = 0


@dataclass
class AttributionResult:
    """Attribution analysis for a file."""

    file: str = ""
    signals: list[AttributionSignal] = field(default_factory=list)
    primary_source: str = "unknown"
    primary_model: str = "unknown"
    ai_probability: float = 0.0
    method: str = "none"  # "ide_hook", "heuristic", "mixed"


# ─────────────────────────────────────────────────────────────────
#  Git trailer patterns
# ─────────────────────────────────────────────────────────────────

_GIT_TRAILERS: list[tuple[str, str, float]] = [
    (r"Co-[Aa]uthored-[Bb]y:.*[Cc]opilot", "github_copilot", 0.9),
    (r"Co-[Aa]uthored-[Bb]y:.*[Cc]laude", "anthropic", 0.9),
    (r"Co-[Aa]uthored-[Bb]y:.*[Gg][Pp][Tt]", "openai", 0.9),
    (r"Co-[Aa]uthored-[Bb]y:.*noreply@anthropic", "anthropic", 0.95),
    (r"Generated-by:.*[Cc]laude", "anthropic", 0.9),
    (r"Generated-by:.*[Gg][Pp][Tt]", "openai", 0.9),
    (r"Generated-by:.*[Cc]opilot", "github_copilot", 0.9),
    (r"AI-assisted", "generic_ai", 0.6),
    (r"^aider:", "aider", 0.8),
    (r"Generated-by:.*[Cc]ursor", "cursor", 0.85),
]

# ─────────────────────────────────────────────────────────────────
#  Heuristic patterns
# ─────────────────────────────────────────────────────────────────

_HEURISTIC_PATTERNS: list[tuple[str, str, str, float]] = [
    # (regex, source, model, confidence)
    (r"# Generated by GitHub Copilot", "github_copilot", "unknown", 0.9),
    (r"# Generated by Claude", "anthropic", "unknown", 0.9),
    (r"# Generated by (?:Chat)?GPT", "openai", "unknown", 0.9),
    (r"# Generated by Cursor", "cursor", "unknown", 0.9),
    (r"# Generated by Cline", "cline", "unknown", 0.9),
    (r"# AI-generated", "generic_ai", "unknown", 0.7),
    # Chatbot preamble patterns (medium confidence)
    (r"(?:I'll |Let me |Here's (?:a|the) ).*(?:implementation|solution)", "generic_ai", "unknown", 0.4),
    (r"(?:Sure|Certainly)[!,]", "generic_ai", "unknown", 0.35),
    # Verbose docstring pattern (low confidence — many humans write these too)
    (r'"""[^"]{300,}"""', "generic_ai", "unknown", 0.3),
    (r"#\s*This (?:function|method|class) (?:does|is|will)", "generic_ai", "unknown", 0.25),
]


# ─────────────────────────────────────────────────────────────────
#  AIAttributor
# ─────────────────────────────────────────────────────────────────


class AIAttributor:
    """Detect which AI model generated code."""

    def analyze_file(
        self,
        filepath: Path,
        content: str | None = None,
        workspace: Path | None = None,
    ) -> AttributionResult:
        """Analyze a file for AI attribution.

        Priority:
        1. IDE hook data (high confidence — we observed the API call)
        2. Git trailer / commit metadata
        3. Code pattern heuristics (low confidence)
        """
        result = AttributionResult(file=str(filepath))

        if workspace is None:
            workspace = filepath.parent

        # --- Priority 1: IDE hook data ---
        hook_signals = self._from_ide_hook(filepath, workspace)
        if hook_signals:
            result.signals.extend(hook_signals)
            result.method = "ide_hook"
            best = max(hook_signals, key=lambda s: s.confidence)
            result.primary_source = best.source
            result.primary_model = best.model
            result.ai_probability = best.confidence
            return result

        # --- Priority 2: Git metadata ---
        git_signals = self._from_git(filepath, workspace)
        if git_signals:
            result.signals.extend(git_signals)

        # --- Priority 3: Code pattern heuristics ---
        if content is None:
            try:
                content = filepath.read_text(encoding="utf-8", errors="replace")
            except OSError:
                return result

        heuristic_signals = self._from_heuristics(content)
        result.signals.extend(heuristic_signals)

        # Combine signals
        if result.signals:
            result.method = "heuristic" if not git_signals else "mixed"
            best = max(result.signals, key=lambda s: s.confidence)
            result.primary_source = best.source
            result.primary_model = best.model
            # Weight: ide_hook signals count full, heuristics are discounted
            total = sum(
                s.confidence if s.method == "ide_hook" else s.confidence * 0.5
                for s in result.signals
            )
            result.ai_probability = min(total / 2.0, 1.0)

        return result

    def analyze_directory(
        self,
        directory: Path,
        extensions: frozenset[str] | None = None,
    ) -> list[AttributionResult]:
        """Analyze all files in a directory."""
        if extensions is None:
            extensions = frozenset({
                ".py", ".js", ".ts", ".jsx", ".tsx", ".go", ".rs",
                ".rb", ".php", ".java", ".cs", ".cpp", ".c",
            })
        results: list[AttributionResult] = []
        for filepath in directory.rglob("*"):
            if filepath.suffix in extensions and filepath.is_file():
                result = self.analyze_file(filepath, workspace=directory)
                if result.ai_probability > 0.0:
                    results.append(result)
        return results

    def _from_ide_hook(
        self,
        filepath: Path,
        workspace: Path,
    ) -> list[AttributionSignal]:
        """Read attribution data from IDE hook JSONL file."""
        signals: list[AttributionSignal] = []
        hook_file = workspace / ".codetrust" / "attribution.jsonl"
        if not hook_file.exists():
            return signals

        try:
            rel_path = str(filepath.relative_to(workspace))
        except ValueError:
            rel_path = str(filepath)

        event_count = 0
        try:
            for line in hook_file.read_text(encoding="utf-8").strip().split("\n"):
                if not line:
                    continue
                event_count += 1
                if event_count > MAX_IDE_HOOK_EVENTS:
                    break
                try:
                    event = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if event.get("active_file") == rel_path:
                    signals.append(AttributionSignal(
                        source=event.get("provider", "unknown"),
                        model=event.get("model", "unknown"),
                        confidence=IDE_HOOK_CONFIDENCE,
                        evidence=(
                            f"IDE hook: {event.get('source_extension', 'unknown')} "
                            f"called {event.get('provider')} at "
                            f"{event.get('timestamp', '')}"
                        ),
                        method="ide_hook",
                    ))
        except OSError:
            pass

        return signals

    def _from_git(
        self,
        filepath: Path,
        workspace: Path,
    ) -> list[AttributionSignal]:
        """Check git log for AI-related trailers on commits touching this file."""
        signals: list[AttributionSignal] = []

        try:
            result = subprocess.run(
                ["git", "log", "-5", "--format=%H|%B", "--", str(filepath)],
                cwd=workspace,
                capture_output=True,
                text=True,
                timeout=5,
            )
            if result.returncode != 0:
                return signals

            for trailer_pattern, source, conf in _GIT_TRAILERS:
                if re.search(trailer_pattern, result.stdout, re.MULTILINE):
                    signals.append(AttributionSignal(
                        source=source,
                        model="unknown",
                        confidence=conf,
                        evidence=f"git trailer: {trailer_pattern}",
                        method="git_trailer",
                    ))
        except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
            pass

        return signals

    def _from_heuristics(self, content: str) -> list[AttributionSignal]:
        """Detect AI patterns from code content."""
        signals: list[AttributionSignal] = []
        seen_sources: set[str] = set()

        for line_num, line in enumerate(content.split("\n"), 1):
            for pattern, source, model, conf in _HEURISTIC_PATTERNS:
                if source in seen_sources:
                    continue  # One signal per source is enough
                if re.search(pattern, line, re.IGNORECASE):
                    signals.append(AttributionSignal(
                        source=source,
                        model=model,
                        confidence=conf,
                        evidence=f"line {line_num}: pattern match",
                        method="heuristic",
                        line=line_num,
                    ))
                    seen_sources.add(source)

        return signals

    def build_report(self, results: list[AttributionResult]) -> str:
        """Build markdown report from attribution results."""
        lines: list[str] = [
            "## AI Attribution Report",
            "",
        ]

        ai_files = [r for r in results if r.ai_probability > 0.0]
        human_files = [r for r in results if r.ai_probability == 0.0]

        lines.append(f"**{len(ai_files)} files** with AI signals, "
                      f"**{len(human_files)} files** human-only")
        lines.append("")

        if not ai_files:
            lines.append("No AI attribution signals detected.")
            return "\n".join(lines)

        for r in sorted(ai_files, key=lambda x: -x.ai_probability):
            conf_pct = f"{r.ai_probability:.0%}"
            model_tag = f" ({r.primary_model})" if r.primary_model != "unknown" else ""
            lines.append(
                f"- **{r.file}** — {r.primary_source}{model_tag} "
                f"[{conf_pct}] via {r.method}"
            )

        return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────
#  Per-line attribution (EU AI Act Article 52 — Transparency)
# ─────────────────────────────────────────────────────────────────


@dataclass
class LineAttribution:
    """Attribution for a single line of code."""

    line_number: int
    commit: str
    author: str
    ai_model: str  # empty string if human-authored
    timestamp: str


def per_line_attribution(filepath: str) -> list[LineAttribution]:
    """Generate per-line attribution by combining git blame with AI trailers.

    For each line: identifies the commit, author, and whether an AI model
    was involved (via AI-Model git trailer on that commit).

    Args:
        filepath: Path to the file to attribute.

    Returns:
        List of LineAttribution, one per line.
    """
    blame_output = _run_git_blame(filepath)
    if not blame_output:
        return []

    # Cache: commit → AI-Model trailer value
    commit_model_cache: dict[str, str] = {}
    results: list[LineAttribution] = []

    current_commit = ""
    current_author = ""
    current_timestamp = ""
    line_num = 0

    for raw_line in blame_output:
        # Porcelain format: first line per block is "commit orig_line final_line [num_lines]"
        parts = raw_line.split()
        if len(parts) >= 3 and len(parts[0]) == 40:
            current_commit = parts[0]
            line_num = int(parts[2]) if parts[2].isdigit() else line_num + 1
        elif raw_line.startswith("author "):
            current_author = raw_line[7:]
        elif raw_line.startswith("author-time "):
            current_timestamp = raw_line[12:]
        elif raw_line.startswith("\t"):
            # This is the actual code line — emit attribution
            if current_commit not in commit_model_cache:
                commit_model_cache[current_commit] = _get_ai_model_trailer(current_commit)
            results.append(LineAttribution(
                line_number=line_num,
                commit=current_commit[:12],
                author=current_author,
                ai_model=commit_model_cache[current_commit],
                timestamp=current_timestamp,
            ))

    return results


def per_line_summary(attributions: list[LineAttribution]) -> dict[str, float]:
    """Aggregate per-line attributions into percentage breakdown.

    Args:
        attributions: List of line attributions.

    Returns:
        Dict of model/human → percentage. E.g. {"claude-opus-4.6": 42.0, "human": 31.0}
    """
    if not attributions:
        return {}

    counts: dict[str, int] = {}
    for attr in attributions:
        key = attr.ai_model if attr.ai_model else "human"
        counts[key] = counts.get(key, 0) + 1

    total = len(attributions)
    return {k: round(v / total * 100, 1) for k, v in counts.items()}


def _run_git_blame(filepath: str) -> list[str]:
    """Run git blame in porcelain format."""
    import subprocess

    try:
        result = subprocess.run(
            ["git", "blame", "--porcelain", filepath],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode != 0:
            return []
        return result.stdout.splitlines()
    except (subprocess.TimeoutExpired, OSError):
        return []


_COAUTHOR_AI_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"noreply@anthropic", re.IGNORECASE), "claude"),
    (re.compile(r"\bclaude\b", re.IGNORECASE), "claude"),
    (re.compile(r"\bcopilot\b", re.IGNORECASE), "github_copilot"),
    (re.compile(r"\b(?:chat)?gpt\b", re.IGNORECASE), "gpt"),
    (re.compile(r"\bcursor\b", re.IGNORECASE), "cursor"),
    (re.compile(r"\baider\b", re.IGNORECASE), "aider"),
    (re.compile(r"\bcline\b", re.IGNORECASE), "cline"),
]


def _get_ai_model_trailer(commit: str) -> str:
    """Look up AI authorship for a commit.

    Checks two trailer formats:
    1. ``AI-Model: <name>`` — explicit format (legacy/internal use)
    2. ``Co-Authored-By: <ai>`` — community standard used by Claude Code,
       GitHub Copilot, Cursor, Aider, Cline. Maps the AI name to a
       canonical model id.

    Returns empty string if no AI signature found (line is human-authored).
    """
    import subprocess

    if not commit or len(commit) < 7:
        return ""
    try:
        # Try explicit AI-Model trailer first.
        explicit = subprocess.run(
            ["git", "log", "-1", "--format=%(trailers:key=AI-Model,valueonly)", commit],
            capture_output=True, text=True, timeout=5,
        )
        explicit_value = explicit.stdout.strip()
        if explicit_value:
            return explicit_value

        # Fall back to scanning Co-Authored-By trailers in the full commit body.
        body = subprocess.run(
            ["git", "log", "-1", "--format=%B", commit],
            capture_output=True, text=True, timeout=5,
        )
        for line in body.stdout.splitlines():
            if not line.lower().startswith("co-authored-by:"):
                continue
            for pattern, model in _COAUTHOR_AI_PATTERNS:
                if pattern.search(line):
                    return model
    except (subprocess.TimeoutExpired, OSError):
        return ""

    return ""
