"""OWASP Agentic Security Initiative (ASI) 2026 compliance mapping.

Maps CodeTrust governance capabilities to recognized security frameworks.
Each mapping is verified against actual code with file paths and line numbers.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from typing import Literal

CoverageLevel = Literal["full", "partial", "planned"]

SUPPORTED_FRAMEWORKS: dict[str, str] = {
    "owasp-asi-2026": "OWASP Agentic Security Initiative Top 10 (2026)",
    "eu-ai-act": "EU AI Act — High-Risk AI System Requirements",
    "nist-ai-rmf": "NIST AI Risk Management Framework 1.0",
    "nis2": "NIS2 Directive (EU 2022/2555) — Art. 21 Cybersecurity Risk-Management Measures",
}


@dataclass(frozen=True)
class EvidenceItem:
    """A single piece of verified implementation evidence."""

    file: str
    function_or_component: str
    detail: str


@dataclass(frozen=True)
class RiskMapping:
    """Mapping of a single framework risk to CodeTrust capabilities."""

    risk_id: str
    risk_name: str
    description: str
    codetrust_coverage: list[str]
    coverage_level: CoverageLevel
    evidence: list[EvidenceItem]
    gap: str


@dataclass(frozen=True)
class ComplianceReport:
    """Complete compliance report for a framework."""

    framework_id: str
    framework_name: str
    generated_by: str
    risks: list[RiskMapping]

    def to_dict(self) -> dict:
        """Serialize to a JSON-safe dictionary."""
        return asdict(self)

    def to_json(self, indent: int = 2) -> str:
        """Serialize to JSON string."""
        return json.dumps(self.to_dict(), indent=indent)

    def to_markdown(self) -> str:
        """Render as a Markdown compliance report."""
        lines: list[str] = [
            f"# {self.framework_name}",
            "",
            f"**Generated by:** {self.generated_by}",
            "",
            _coverage_summary_table(self.risks),
            "",
        ]
        for risk in self.risks:
            lines.append(f"## {risk.risk_id}: {risk.risk_name}")
            lines.append("")
            lines.append(f"**Description:** {risk.description}")
            lines.append("")
            lines.append(f"**Coverage:** `{risk.coverage_level}`")
            lines.append("")
            lines.append("**CodeTrust capabilities:**")
            for cap in risk.codetrust_coverage:
                lines.append(f"- {cap}")
            lines.append("")
            if risk.evidence:
                lines.append("**Evidence:**")
                lines.append("")
                lines.append("| File | Component | Detail |")
                lines.append("|------|-----------|--------|")
                for ev in risk.evidence:
                    lines.append(f"| `{ev.file}` | {ev.function_or_component} | {ev.detail} |")
                lines.append("")
            if risk.gap:
                lines.append(f"**Gap:** {risk.gap}")
                lines.append("")
        return "\n".join(lines)


def _coverage_summary_table(risks: list[RiskMapping]) -> str:
    """Build a Markdown summary table of all risks."""
    lines = [
        "| Risk ID | Risk Name | Coverage |",
        "|---------|-----------|----------|",
    ]
    for r in risks:
        icon = {"full": "🟢", "partial": "🟡", "planned": "🔴"}[r.coverage_level]
        lines.append(f"| {r.risk_id} | {r.risk_name} | {icon} {r.coverage_level} |")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# OWASP ASI 2026 mapping — verified against code 2026-03-30
# ---------------------------------------------------------------------------

_OWASP_ASI_2026: list[RiskMapping] = [
    RiskMapping(
        risk_id="OWASP-ASI-01",
        risk_name="Prompt Injection",
        description="Malicious input manipulates agent behavior, bypasses instructions, or exfiltrates data.",
        codetrust_coverage=[
            "Gateway interceptor — 33 BLOCK patterns for terminal commands",
            "BASH_ENV guard — 3 core rules for universal real-time shell enforcement",
            "PreToolUse gateway hook — 42 blocked patterns before execution",
            "Interpreter inner-string validation — blocks python3 -c / node -e injection",
            "Governance file protection — 13 protected paths prevent rule tampering",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/gateway/interceptor.py",
                function_or_component="_TERMINAL_RULES",
                detail="Lines 163-534: 33 BLOCK-level gateway rules",
            ),
            EvidenceItem(
                file="src/templates/bash_env_guard.sh",
                function_or_component="codetrust_guard()",
                detail="Lines 41-77: 3 core rules — heredoc, git push, rm -rf",
            ),
            EvidenceItem(
                file="src/templates/pretooluse_gateway_hook.py",
                function_or_component="BLOCKED_PATTERNS",
                detail="Lines 116-402: 42 gateway rule IDs across 12 security categories",
            ),
            EvidenceItem(
                file="src/gateway/interceptor.py",
                function_or_component="_check_interpreter_inner_string()",
                detail="Lines 131-156: validates inner commands for python/node/ruby/perl -c/-e",
            ),
            EvidenceItem(
                file="src/templates/pretooluse_file_write_hook.py",
                function_or_component="PROTECTED_PATH_PATTERNS",
                detail="Lines 24-90: 13 protected paths block governance file tampering",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="OWASP-ASI-02",
        risk_name="Insecure Tool Use",
        description="Agent invokes tools without validation, enabling command injection or unauthorized operations.",
        codetrust_coverage=[
            "MCP Gateway proxy — 19 validated tool wrappers",
            "validate_command — checks terminal commands against 33 BLOCK patterns",
            "validate_file_write — checks file writes for secrets and protected paths",
            "validate_package — validates package names before installation",
            "validate_file_delete — validates file deletion requests",
            "Delta-only validation — validates new content, not entire file",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/gateway/server.py",
                function_or_component="validate_command()",
                detail="Line 539: intercepts and validates terminal commands",
            ),
            EvidenceItem(
                file="src/gateway/server.py",
                function_or_component="validate_file_write()",
                detail="Line 592: intercepts file writes, checks secrets and protected paths",
            ),
            EvidenceItem(
                file="src/gateway/server.py",
                function_or_component="validate_package()",
                detail="Line 668: validates package names against registry before installation",
            ),
            EvidenceItem(
                file="src/gateway/server.py",
                function_or_component="validate_file_delete()",
                detail="Line 636: validates file deletion against protected paths",
            ),
            EvidenceItem(
                file="src/gateway/server.py",
                function_or_component="proxy_replace_string_in_file()",
                detail="Lines 901-955: delta-only validation — validates new_string only",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="OWASP-ASI-03",
        risk_name="Excessive Agency",
        description="Agent takes actions beyond intended scope without human oversight or approval.",
        codetrust_coverage=[
            "Session action-count limiter — configurable per-session tool invocation cap",
            "Commit Policy Engine — allowed_models, models_blocked, max_ai_ratio enforcement",
            "codetrust doctor — verifies all 9 enforcement layers are active",
            "Trusted Session mechanism — explicit human approval for elevated actions",
            "Pre-action validation — checks plans before code is written",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/gateway/server.py",
                function_or_component="_check_session_action_limit()",
                detail="Per-session action counter, configurable via CODETRUST_SESSION_ACTION_LIMIT (default 500)",
            ),
            EvidenceItem(
                file="src/services/commit_policy.py",
                function_or_component="PolicyConfig",
                detail="Lines 40-65: allowed_models, models_blocked, max_ai_ratio, require_human_review",
            ),
            EvidenceItem(
                file="src/gateway/server.py",
                function_or_component="begin_trusted_session()",
                detail="Line 1261: explicit human-initiated trusted session with justification",
            ),
            EvidenceItem(
                file="src/server.py",
                function_or_component="codetrust_pre_action()",
                detail="Line 229: validates task plans before code execution begins",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="OWASP-ASI-04",
        risk_name="Unauthorized Actions",
        description="Agent performs operations it should not be permitted to execute.",
        codetrust_coverage=[
            "PreToolUse hooks — intercept EVERY Bash command before execution",
            "Allow-list audit — detects 9 dangerous bypass patterns in settings",
            "Protected file paths — 13 governance files cannot be modified by agents",
            "Gateway interceptor — blocks git push, rm -rf, eval, privilege escalation",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/templates/pretooluse_gateway_hook.py",
                function_or_component="BLOCKED_PATTERNS",
                detail="Lines 116-402: 44 blocked patterns covering 12 security categories",
            ),
            EvidenceItem(
                file="src/cli.py",
                function_or_component="audit_allow_list()",
                detail="Lines 3117-3137: checks for 9 dangerous allow-list bypass patterns",
            ),
            EvidenceItem(
                file="src/templates/pretooluse_file_write_hook.py",
                function_or_component="PROTECTED_PATH_PATTERNS",
                detail="Lines 24-90: .claude/settings.json, .codetrust.toml, CLAUDE.md, .ssh/, .aws/, etc.",
            ),
            EvidenceItem(
                file="src/gateway/interceptor.py",
                function_or_component="_TERMINAL_RULES",
                detail="Lines 163-534: 33 patterns including git push, rm -rf, eval, chmod 777",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="OWASP-ASI-05",
        risk_name="Improper Error Handling",
        description="Agent errors expose internal state, crash governance, or degrade to unprotected mode.",
        codetrust_coverage=[
            "Fail-open design — hooks return 0 on exception (documented trade-off)",
            "Hook health-check — doctor tests both BLOCK and ALLOW to detect silent failures",
            "Append-only audit trail — all actions logged regardless of outcome",
            "Non-blocking audit I/O — audit write failures buffered, never crash",
            "codetrust doctor — verifies enforcement layers are operational",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/templates/pretooluse_gateway_hook.py",
                function_or_component="main()",
                detail="Lines 457-461: except Exception → return 0 (fail-open, documented)",
            ),
            EvidenceItem(
                file="src/templates/pretooluse_file_write_hook.py",
                function_or_component="main()",
                detail="Lines 194-198: JSON/Exception → return 0 with 'Hook must not crash' comment",
            ),
            EvidenceItem(
                file="src/gateway/audit.py",
                function_or_component="AuditLogger.log()",
                detail="Lines 100-103: OSError → buffer entry, log warning, never crash",
            ),
            EvidenceItem(
                file="src/cli.py",
                function_or_component="cmd_doctor()",
                detail="Line 4854: operational verification of all enforcement layers",
            ),
            EvidenceItem(
                file="src/cli.py",
                function_or_component="_doctor_check_pretooluse_hooks()",
                detail="Hook health-check: tests BLOCK (git push) AND ALLOW (ls -la) to detect silent failures",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="OWASP-ASI-06",
        risk_name="Supply Chain Vulnerabilities",
        description="Agent installs malicious or vulnerable packages via hallucinated or compromised dependencies.",
        codetrust_coverage=[
            "Import verification — detects hallucinated packages across 8 languages",
            "Registry verification — validates against PyPI, npm, Go Proxy, RubyGems, Maven, NuGet, Packagist",
            "Vulnerability scanning — OSV database with NVD severity enrichment",
            "License compliance checking — permissive/copyleft/strong-copyleft classification",
            "Package validation — BLOCK on NOT_FOUND registry status",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/services/import_verifier.py",
                function_or_component="async_verify_file_imports()",
                detail="Line 236: verifies imports against registries, flags NOT_FOUND as hallucination",
            ),
            EvidenceItem(
                file="src/services/registry.py",
                function_or_component="RegistryService",
                detail="Lines 89-893: PyPI, npm, Go Proxy, RubyGems verification with real HTTP calls",
            ),
            EvidenceItem(
                file="src/services/vulnerability.py",
                function_or_component="VulnerabilityService",
                detail="Lines 113+: OSV API + NVD enrichment for 8 ecosystems",
            ),
            EvidenceItem(
                file="src/services/license_checker.py",
                function_or_component="LicenseService",
                detail="Lines 34-89: permissive/weak-copyleft/strong-copyleft/network-copyleft classification",
            ),
            EvidenceItem(
                file="src/gateway/server.py",
                function_or_component="validate_package()",
                detail="Line 668: BLOCK verdict when package not found in registry",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="OWASP-ASI-07",
        risk_name="Sensitive Information Disclosure",
        description="Agent leaks secrets, credentials, or PII through code, logs, or tool outputs.",
        codetrust_coverage=[
            "File-write hook — 6 secret patterns detected before file is written",
            "Hardcoded secret scan rules — BLOCK severity in static analysis",
            "URL credential redaction — strips passwords from log output",
            "Protected credential paths — .env.production, .ssh/, .aws/, .kube/ blocked",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/templates/pretooluse_file_write_hook.py",
                function_or_component="SECRET_PATTERNS",
                detail="Lines 94-131: API keys, passwords, AWS AKIA, GitHub tokens, Stripe keys, JWTs",
            ),
            EvidenceItem(
                file="src/rules/anti_patterns.py",
                function_or_component="hardcoded_secret",
                detail="Lines 53-68: BLOCK severity rule for api_key/secret/password/token patterns",
            ),
            EvidenceItem(
                file="src/services/cache.py",
                function_or_component="_redact_url()",
                detail="Lines 18-26: strips password from Redis URLs before logging",
            ),
            EvidenceItem(
                file="src/templates/pretooluse_file_write_hook.py",
                function_or_component="PROTECTED_PATH_PATTERNS",
                detail="Lines 52-72: blocks writes to .env.production, .ssh/, .aws/, .kube/",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="OWASP-ASI-08",
        risk_name="Sandboxing Failures",
        description="Agent-generated code executes without isolation, risking host system compromise.",
        codetrust_coverage=[
            "Docker sandbox — isolated execution with resource limits",
            "Network isolation — --network=none blocks all container networking",
            "Read-only filesystem — --read-only prevents persistent writes",
            "Resource limits — memory cap, 1 CPU, 64 PIDs, no-new-privileges",
            "Language support — Python, JavaScript, TypeScript, Go, Rust",
            "Output limits — 50KB max output, configurable timeout",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/services/sandbox.py",
                function_or_component="SandboxService",
                detail="Line 58: Docker-based isolated execution with resource limits",
            ),
            EvidenceItem(
                file="src/services/sandbox.py",
                function_or_component="_build_docker_command()",
                detail="Line 187: --network=none, --read-only, --memory, --cpus=1, --pids-limit=64, --security-opt=no-new-privileges",
            ),
            EvidenceItem(
                file="src/api.py",
                function_or_component="/v1/sandbox/run",
                detail="Line 2288: POST endpoint for sandboxed code execution",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="OWASP-ASI-09",
        risk_name="Excessive Permissions",
        description="Agent operates with broader permissions than necessary for its task.",
        codetrust_coverage=[
            "Allow-list audit — detects 9 dangerous permission bypass patterns",
            "Preventive enforcement — codetrust init exits 1 when dangerous entries found",
            "Policy integrity verification — SHA-256 HMAC of governance files",
            "Governance integrity MCP tool — runtime hash verification",
            "Protected path enforcement — credential directories blocked",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/cli.py",
                function_or_component="audit_allow_list()",
                detail="Lines 3117-3137: 9 patterns — git push, rm -rf, eval, curl|sh, sudo su, chmod 777, dd, mkfs, docker --privileged",
            ),
            EvidenceItem(
                file="src/cli.py",
                function_or_component="cmd_init()",
                detail="codetrust init returns exit 1 when dangerous allow-list entries detected — preventive, not just detective",
            ),
            EvidenceItem(
                file="src/gateway/policy_integrity.py",
                function_or_component="verify_policy_integrity()",
                detail="Lines 18-60: SHA-256 HMAC verification of 5 governance files",
            ),
            EvidenceItem(
                file="src/gateway/server.py",
                function_or_component="governance_integrity()",
                detail="Line 1468: MCP tool for runtime governance file hash comparison",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="OWASP-ASI-10",
        risk_name="Logging & Monitoring Gaps",
        description="Insufficient audit trail makes it impossible to detect or investigate agent misbehavior.",
        codetrust_coverage=[
            "Append-only JSONL audit trail — every action logged with verdict and rule_id",
            "Audit history MCP tool — query logs by time range, verdict, format",
            "Telemetry system — privacy-preserving anonymous aggregation",
            "Completion Hallucination Detection — verifies agent claims against evidence",
            "CLI audit command — export in table/CEF/LEEF/syslog/JSON formats",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/gateway/audit.py",
                function_or_component="AuditLogger",
                detail="Lines 56-321: append-only JSONL with timestamp, verdict, rule_id, action, suggestion",
            ),
            EvidenceItem(
                file="src/gateway/server.py",
                function_or_component="audit_history()",
                detail="Line 1173: MCP tool with hours/verdict/limit/export_format parameters",
            ),
            EvidenceItem(
                file="src/services/telemetry.py",
                function_or_component="TelemetryIngestEvent",
                detail="Lines 119-144: privacy-preserving event model, no code/paths/IPs",
            ),
            EvidenceItem(
                file="src/services/completion_hallucination.py",
                function_or_component="verify_claims()",
                detail="Line 122+: detects unverified agent completion claims across 9 marker patterns",
            ),
            EvidenceItem(
                file="src/cli.py",
                function_or_component="cmd_audit()",
                detail="Lines 5701-5721: CLI with table/CEF/LEEF/syslog/JSON export formats",
            ),
        ],
        gap="",
    ),
]


# ---------------------------------------------------------------------------
# EU AI Act mapping (high-risk AI system requirements)
# ---------------------------------------------------------------------------

_EU_AI_ACT: list[RiskMapping] = [
    RiskMapping(
        risk_id="EU-AI-ACT-01",
        risk_name="Risk Management System",
        description="Continuous risk identification and mitigation throughout the AI system lifecycle.",
        codetrust_coverage=[
            "Formal risk register — TOML-based with likelihood, impact, score, mitigation, owner, review date",
            "CLI: codetrust risk-register init/add/list — full CRUD",
            "8-layer enforcement architecture verified by codetrust doctor",
            "Developer risk scoring per author",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/services/risk_register.py",
                function_or_component="RiskRegister",
                detail="Formal risk register: Risk dataclass with risk_score, add_risk, save/load TOML, export JSON",
            ),
            EvidenceItem(
                file="src/cli.py",
                function_or_component="cmd_risk_register()",
                detail="CLI: codetrust risk-register init/add/list with full CRUD operations",
            ),
            EvidenceItem(
                file="src/services/developer_risk.py",
                function_or_component="DeveloperRiskService",
                detail="Per-author risk profiling based on commit patterns",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="EU-AI-ACT-02",
        risk_name="Data Governance",
        description="Training and validation data must be relevant, representative, and free of bias.",
        codetrust_coverage=[
            "Privacy report — documents all data collected, storage, retention, opt-out",
            "CLI: codetrust privacy — structured data governance report",
            "No PII by design — anonymous installation IDs, no code content transmitted",
            "GDPR compliance documented: retention policy, purge command, telemetry disable",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/services/privacy.py",
                function_or_component="generate_privacy_report()",
                detail="4 data categories documented: scan events, installation ID, audit log, attribution",
            ),
            EvidenceItem(
                file="src/services/privacy.py",
                function_or_component="NOT_COLLECTED",
                detail="6 explicit exclusions: source code, file paths, IPs, names, git content, credentials",
            ),
            EvidenceItem(
                file="src/cli.py",
                function_or_component="cmd_privacy()",
                detail="CLI: codetrust privacy — generates structured privacy and data governance report",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="EU-AI-ACT-03",
        risk_name="Technical Documentation",
        description="Maintain documentation covering system purpose, capabilities, limitations, and risks.",
        codetrust_coverage=[
            "Conformity assessment — automated, dated, versioned, signed report",
            "CLI: codetrust assess — runs doctor + compliance + DoD + risk register",
            "SHA-256 signed reports for audit trail integrity",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/services/conformity_assessment.py",
                function_or_component="run_assessment()",
                detail="6 sections: doctor, OWASP, EU AI Act, NIST, DoD, risk register — each as subprocess",
            ),
            EvidenceItem(
                file="src/services/conformity_assessment.py",
                function_or_component="sign_report()",
                detail="SHA-256 signature of report content for integrity verification",
            ),
            EvidenceItem(
                file="src/cli.py",
                function_or_component="cmd_assess()",
                detail="CLI: codetrust assess — full conformity assessment with exit code enforcement",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="EU-AI-ACT-04",
        risk_name="Record-Keeping (Logging)",
        description="Automatic logging of events for traceability throughout the system lifecycle.",
        codetrust_coverage=[
            "Append-only JSONL audit trail",
            "Telemetry event recording",
            "CLI audit export (CEF/LEEF/syslog/JSON)",
            "Completion hallucination detection with evidence trail",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/gateway/audit.py",
                function_or_component="AuditLogger",
                detail="Lines 56-321: append-only, timestamp+verdict+rule_id+action per entry",
            ),
            EvidenceItem(
                file="src/cli.py",
                function_or_component="cmd_audit()",
                detail="Lines 5701-5721: export in 5 enterprise SIEM formats",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="EU-AI-ACT-05",
        risk_name="Transparency",
        description="Users must be informed they are interacting with an AI system.",
        codetrust_coverage=[
            "Per-line attribution — git blame + AI-Model trailer = each line → human or model",
            "Per-line summary — aggregated percentage breakdown per model/human",
            "Per-commit attribution via git trailers (AI-Model, AI-Editor)",
            "vscode.lm API — real-time model detection",
            "Shadow AI detection — identifies undisclosed AI tool usage",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/services/ai_attribution.py",
                function_or_component="per_line_attribution()",
                detail="Combines git blame --porcelain with AI-Model trailer per commit for per-line attribution",
            ),
            EvidenceItem(
                file="src/services/ai_attribution.py",
                function_or_component="per_line_summary()",
                detail="Aggregates: e.g. '42% claude-opus-4.6, 31% human, 27% gpt-4o'",
            ),
            EvidenceItem(
                file="src/services/shadow_ai.py",
                function_or_component="ShadowAIService",
                detail="Detects undisclosed AI tool usage in development environments",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="EU-AI-ACT-06",
        risk_name="Human Oversight",
        description="Effective human oversight mechanisms to prevent or minimize risks.",
        codetrust_coverage=[
            "Pre-commit hook — human reviews before commit",
            "GitHub Action — human reviews before merge",
            "Trusted session — explicit human approval for elevated actions",
            "git push prohibition — human pushes manually",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/templates/pretooluse_gateway_hook.py",
                function_or_component="gateway_git_push",
                detail="Blocks all git push — forces human to push manually",
            ),
            EvidenceItem(
                file="src/gateway/server.py",
                function_or_component="begin_trusted_session()",
                detail="Line 1261: requires human justification for elevated permissions",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="EU-AI-ACT-07",
        risk_name="Accuracy, Robustness, Cybersecurity",
        description="AI systems must be resilient, accurate, and secure against adversarial attacks.",
        codetrust_coverage=[
            "Red team — 25 automated evasion tests against own enforcement layers",
            "CLI: codetrust red-team — tests heredoc variants, encoding bypass, interpreter injection, path traversal",
            "Evasion catalog: heredoc, base64, hex, python -c, variable expansion, split commands, unicode",
            "FP rate benchmarks on real code (Flask 0%, Django 8.6%)",
            "Policy integrity SHA-256 HMAC tamper detection",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/services/red_team.py",
                function_or_component="EVASION_TESTS",
                detail="25 evasion tests across 11 categories: heredoc, encoding, interpreter, variable, path, whitespace, split, privilege, exfiltration, container, safe",
            ),
            EvidenceItem(
                file="src/services/red_team.py",
                function_or_component="run_red_team()",
                detail="Runs each evasion against gateway hook as subprocess, reports blocked/bypassed",
            ),
            EvidenceItem(
                file="src/cli.py",
                function_or_component="cmd_red_team()",
                detail="CLI: codetrust red-team — full adversarial robustness report",
            ),
        ],
        gap="",
    ),
]


# ---------------------------------------------------------------------------
# NIST AI RMF mapping
# ---------------------------------------------------------------------------

_NIST_AI_RMF: list[RiskMapping] = [
    RiskMapping(
        risk_id="NIST-RMF-GOVERN",
        risk_name="Govern",
        description="Policies, processes, and accountability structures for AI risk management.",
        codetrust_coverage=[
            "Governance report — formal documentation from policy config, enforcement layers, DoD, risk register, compliance",
            "CLI: codetrust governance-report — generates complete governance documentation",
            "Policy as code in .codetrust.toml with integrity verification",
            "9 enforcement layers verified by codetrust doctor",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/services/governance_report.py",
                function_or_component="generate_governance_report()",
                detail="5 sections: policy config, enforcement architecture, DoD, risk register, compliance frameworks",
            ),
            EvidenceItem(
                file="src/cli.py",
                function_or_component="cmd_governance_report()",
                detail="CLI: codetrust governance-report — formal governance documentation",
            ),
            EvidenceItem(
                file="src/gateway/policy_integrity.py",
                function_or_component="verify_policy_integrity()",
                detail="SHA-256 HMAC verification of 5 governance files",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="NIST-RMF-MAP",
        risk_name="Map",
        description="Identify and categorize AI risks in context.",
        codetrust_coverage=[
            "Automated risk map — generated from scan results, taint analysis, fleet discovery, allow-list audit",
            "CLI: codetrust risk-map — risk heatmap with severity distribution and top 10 risks",
            "Multi-source risk catalog: scan findings, registered risks, allow-list bypasses",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/services/risk_map.py",
                function_or_component="generate_risk_map()",
                detail="3 sources: allow-list audit (CRITICAL), scan reports (HIGH/MEDIUM), risk register (scored)",
            ),
            EvidenceItem(
                file="src/services/risk_map.py",
                function_or_component="RiskMap.top_risks",
                detail="Top 10 risks sorted by severity (CRITICAL first), with category and source",
            ),
            EvidenceItem(
                file="src/cli.py",
                function_or_component="cmd_risk_map()",
                detail="CLI: codetrust risk-map — automated risk catalog with heatmap",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="NIST-RMF-MEASURE",
        risk_name="Measure",
        description="Quantify and track AI risks using appropriate metrics.",
        codetrust_coverage=[
            "Formal metrics report — SLO format: target, current, MEETING/NOT MEETING",
            "CLI: codetrust metrics — scan rules, suggestion coverage, taint defs, compliance, gateway rules",
            "Telemetry — scan counts, finding severity distribution, impact categories",
            "FP rate benchmarks — measured against Flask, Django, own code",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/services/metrics_report.py",
                function_or_component="generate_metrics_report()",
                detail="6 metrics with SLO targets: scan rules, suggestion coverage, taint defs, compliance, gateway rules, tests",
            ),
            EvidenceItem(
                file="src/services/metrics_report.py",
                function_or_component="MetricsReport.summary",
                detail="SLO summary: 'X/Y SLOs meeting target'",
            ),
            EvidenceItem(
                file="src/cli.py",
                function_or_component="cmd_metrics()",
                detail="CLI: codetrust metrics — formal SLO metrics report",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="NIST-RMF-MANAGE",
        risk_name="Manage",
        description="Prioritize and act on AI risks identified through governance processes.",
        codetrust_coverage=[
            "Treatment plan — import BLOCK findings, track status (open/in_progress/mitigated/accepted/false_positive)",
            "CLI: codetrust treatment-plan show/import — finding-level treatment tracking",
            "Progress tracking: 'X/Y findings addressed (Z%)'",
            "Connected to guided remediation — each finding has auto-fix instruction",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/services/treatment_plan.py",
                function_or_component="TreatmentPlan",
                detail="TOML-based treatment tracking with 5 statuses, progress calculation, BLOCK import",
            ),
            EvidenceItem(
                file="src/services/treatment_plan.py",
                function_or_component="import_findings_to_plan()",
                detail="Imports BLOCK findings from JSON scan reports, deduplicates by finding_id",
            ),
            EvidenceItem(
                file="src/cli.py",
                function_or_component="cmd_treatment_plan()",
                detail="CLI: codetrust treatment-plan show/import — risk treatment management",
            ),
        ],
        gap="",
    ),
]


# ---------------------------------------------------------------------------
# NIS2 Directive (EU 2022/2555), Article 21(2) cybersecurity risk-management
# measures. Folded in from the Guardian DevSecOps work (built for a Telia
# regulatory context). Honest scope: CodeTrust covers the technical
# secure-development measures (d, e, f) well; organizational measures —
# incident reporting to CSIRTs, business continuity, MFA, training — are
# process obligations, not code, and are marked as gaps rather than claimed.
_NIS2: list[RiskMapping] = [
    RiskMapping(
        risk_id="NIS2-21d",
        risk_name="Supply chain security",
        description=(
            "Art. 21(2)(d): security related to supply chains, including the "
            "relationship between each entity and its direct suppliers/providers."
        ),
        codetrust_coverage=[
            "Live import verification against 8 package registries (PyPI, npm, crates.io, Go, Maven, NuGet, RubyGems, Packagist)",
            "Hallucinated-package detection — blocks dependencies that do not exist on any registry",
            "Dependency vulnerability scanning (CVE/GHSA) via codetrust vuln",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/services/import_verifier.py",
                function_or_component="import verification",
                detail="Verifies every import against live registries; NOT_FOUND packages are flagged",
            ),
            EvidenceItem(
                file="src/services/vulnerability.py",
                function_or_component="dependency CVE/GHSA scan",
                detail="codetrust vuln — known-vulnerability scan of declared dependencies",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="NIS2-21e",
        risk_name="Security in development and vulnerability handling",
        description=(
            "Art. 21(2)(e): security in network and information systems acquisition, "
            "development and maintenance, including vulnerability handling and disclosure."
        ),
        codetrust_coverage=[
            "Static analysis engine (2,928 rules) covering injection, secrets, unsafe config, destructive operations",
            "Pre-commit and CI gates enforce findings at commit/PR time (opt-in via commit_gate)",
            "Reproducible detection benchmark with measured recall and false-positive rate",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/services/static_analyzer.py",
                function_or_component="StaticAnalyzer.scan_code()",
                detail="Canonical detection engine; severities BLOCK/WARN/INFO",
            ),
            EvidenceItem(
                file="src/services/detection_benchmark.py",
                function_or_component="run_detection_benchmark()",
                detail="Honest recall + false-positive measurement on a labeled corpus",
            ),
        ],
        gap="Coordinated vulnerability disclosure intake is an organizational process, not provided by the tool.",
    ),
    RiskMapping(
        risk_id="NIS2-21f",
        risk_name="Effectiveness assessment",
        description=(
            "Art. 21(2)(f): policies and procedures to assess the effectiveness of "
            "cybersecurity risk-management measures."
        ),
        codetrust_coverage=[
            "Definition of Done gates (codetrust dod) run compliance, tests, and lint as pass/fail acceptance criteria",
            "codetrust doctor verifies enforcement layers are active",
            "Detection benchmark quantifies engine effectiveness",
        ],
        coverage_level="full",
        evidence=[
            EvidenceItem(
                file="src/services/compliance.py",
                function_or_component="get_compliance_report()",
                detail="Framework coverage mapping with per-control evidence",
            ),
            EvidenceItem(
                file="src/services/detection_benchmark.py",
                function_or_component="run_detection_benchmark()",
                detail="Measured recall/false-positive rate as an effectiveness metric",
            ),
        ],
        gap="",
    ),
    RiskMapping(
        risk_id="NIS2-21a",
        risk_name="Risk analysis and security policies",
        description=(
            "Art. 21(2)(a): policies on risk analysis and information system security."
        ),
        codetrust_coverage=[
            "Policy-as-code in .codetrust.toml with SHA-256 integrity verification",
            "Governance configuration with auditable, version-controlled policy",
        ],
        coverage_level="partial",
        evidence=[
            EvidenceItem(
                file="src/gateway/policies.py",
                function_or_component="GovernanceConfig / PolicyEngine",
                detail="Declarative, version-controlled security policy enforced at runtime",
            ),
        ],
        gap="Organization-wide risk-analysis methodology and sign-off remain a management process.",
    ),
    RiskMapping(
        risk_id="NIS2-21b",
        risk_name="Incident handling",
        description="Art. 21(2)(b): incident handling.",
        codetrust_coverage=[
            "Append-only audit log of every allowed/warned/blocked agent action",
            "Session view groups activity into reviewable units (codetrust sessions)",
            "Gateway interception detects and blocks dangerous actions before execution",
        ],
        coverage_level="partial",
        evidence=[
            EvidenceItem(
                file="src/gateway/audit.py",
                function_or_component="AuditLogger",
                detail="JSONL audit trail for detection, forensics, and review",
            ),
            EvidenceItem(
                file="src/gateway/sessions.py",
                function_or_component="group_into_sessions()",
                detail="Per-session activity review with verdict breakdown",
            ),
        ],
        gap="Mandatory incident reporting to national CSIRTs (Art. 23) is an organizational obligation, not automated by the tool.",
    ),
    RiskMapping(
        risk_id="NIS2-21h",
        risk_name="Cryptography and access control",
        description=(
            "Art. 21(2)(h)+(i): use of cryptography/encryption; human-resources "
            "security, access-control policies and asset management."
        ),
        codetrust_coverage=[
            "Detection of weak cryptography and plaintext secrets in code",
            "Hardcoded-credential and secret-exposure rules",
            "Protected-path policy for sensitive files (e.g. .env, keys)",
        ],
        coverage_level="partial",
        evidence=[
            EvidenceItem(
                file="src/services/static_analyzer.py",
                function_or_component="crypto/secret rules",
                detail="Flags weak ciphers, plaintext passwords, hardcoded secrets",
            ),
        ],
        gap="Key management, MFA, and identity/access provisioning are infrastructure controls outside the tool's scope.",
    ),
    RiskMapping(
        risk_id="NIS2-21c",
        risk_name="Business continuity",
        description="Art. 21(2)(c): business continuity, backup management, crisis management.",
        codetrust_coverage=[],
        coverage_level="planned",
        evidence=[],
        gap="Out of scope — business continuity and backup are operational/infrastructure measures, not code governance.",
    ),
]


# Public API
# ---------------------------------------------------------------------------

_FRAMEWORK_REGISTRY: dict[str, list[RiskMapping]] = {
    "owasp-asi-2026": _OWASP_ASI_2026,
    "eu-ai-act": _EU_AI_ACT,
    "nist-ai-rmf": _NIST_AI_RMF,
    "nis2": _NIS2,
}


def list_frameworks() -> dict[str, str]:
    """Return supported framework IDs and their display names."""
    return dict(SUPPORTED_FRAMEWORKS)


def get_compliance_report(framework_id: str) -> ComplianceReport:
    """Generate a compliance report for the given framework.

    Args:
        framework_id: One of the supported framework identifiers.

    Returns:
        ComplianceReport with all risk mappings and evidence.

    Raises:
        ValueError: If framework_id is not supported.
    """
    if framework_id not in _FRAMEWORK_REGISTRY:
        supported = ", ".join(sorted(_FRAMEWORK_REGISTRY))
        msg = f"Unknown framework '{framework_id}'. Supported: {supported}"
        raise ValueError(msg)

    name = SUPPORTED_FRAMEWORKS[framework_id]
    risks = _FRAMEWORK_REGISTRY[framework_id]

    return ComplianceReport(
        framework_id=framework_id,
        framework_name=name,
        generated_by="CodeTrust AI Governance Platform",
        risks=list(risks),
    )


def compliance_summary(report: ComplianceReport) -> str:
    """Build human-readable summary string like '10/10 full' or '6/10 full, 4/10 partial'.

    Args:
        report: A compliance report to summarize.

    Returns:
        Summary string.
    """
    total = len(report.risks)
    full = sum(1 for r in report.risks if r.coverage_level == "full")
    partial = sum(1 for r in report.risks if r.coverage_level == "partial")
    planned = sum(1 for r in report.risks if r.coverage_level == "planned")

    parts: list[str] = [f"{full}/{total} full"]
    if partial:
        parts.append(f"{partial}/{total} partial")
    if planned:
        parts.append(f"{planned}/{total} planned")
    return ", ".join(parts)


def is_fully_compliant(framework_id: str) -> bool:
    """Check if ALL risks in a framework have full coverage.

    Args:
        framework_id: Framework identifier.

    Returns:
        True only if every risk has coverage_level == 'full'.

    Raises:
        ValueError: If framework_id is not supported.
    """
    report = get_compliance_report(framework_id)
    return all(r.coverage_level == "full" for r in report.risks)


# ---------------------------------------------------------------------------
# Finding → regulation mapping
# ---------------------------------------------------------------------------
# Turns live scan findings into compliance evidence: which regulation articles
# a given class of finding implicates. Folded in from the Guardian DevSecOps
# work (which mapped CWEs → GDPR/PCI-DSS/NIS2/PTS); translated here to
# CodeTrust's impact categories so it rides on the existing scan engine.
#
# This is a judgment mapping of "what regulation does this kind of issue touch",
# not a legal determination. It surfaces exposure for review — it does not
# certify compliance or non-compliance.


@dataclass(frozen=True)
class RegulationRef:
    """A regulation article a finding category implicates."""

    framework: str
    citation: str
    rationale: str


CATEGORY_REGULATION_MAP: dict[str, list[RegulationRef]] = {
    "secrets_exposure": [
        RegulationRef("GDPR", "Art. 32", "Security of processing — exposed credentials risk unauthorized access to personal data"),
        RegulationRef("PCI-DSS", "Req. 3 & 6.5", "Protect stored credentials; secure coding against exposure"),
        RegulationRef("NIS2", "Art. 21(2)(h)(i)", "Cryptography and access-control measures"),
    ],
    "injection_attacks": [
        RegulationRef("NIS2", "Art. 21(2)(e)", "Security in development — vulnerability handling"),
        RegulationRef("PCI-DSS", "Req. 6.5.1", "Injection flaws in secure coding"),
        RegulationRef("GDPR", "Art. 32", "Security of processing against unauthorized access"),
    ],
    "destructive_commands": [
        RegulationRef("NIS2", "Art. 21(2)(e)", "Secure development and maintenance against destructive operations"),
    ],
    "supply_chain": [
        RegulationRef("NIS2", "Art. 21(2)(d)", "Supply-chain security — dependency integrity"),
    ],
    "hallucinations": [
        RegulationRef("NIS2", "Art. 21(2)(d)", "Supply-chain security — non-existent/fabricated dependencies"),
    ],
    "unsafe_config": [
        RegulationRef("NIS2", "Art. 21(2)(e)", "Security in development and maintenance"),
        RegulationRef("GDPR", "Art. 32", "Security of processing — misconfiguration risk"),
    ],
}

_IMPACT_SEVERITIES: frozenset[str] = frozenset({"BLOCK", "WARN"})


@dataclass
class ComplianceImpact:
    """Aggregate of which regulations a set of scan findings implicates."""

    total_findings: int
    by_regulation: dict[str, dict[str, object]]  # "GDPR Art. 32" -> {count, citation, framework, rationale}

    def to_dict(self) -> dict[str, object]:
        return {
            "total_findings": self.total_findings,
            "regulations_implicated": len(self.by_regulation),
            "by_regulation": self.by_regulation,
        }


def map_findings_to_regulations(
    findings: list[dict[str, object]],
) -> ComplianceImpact:
    """Map scan findings to the regulation articles they implicate.

    Only BLOCK/WARN findings count. Each finding's rule is resolved to an
    impact category, then to the regulation references for that category.
    """
    from src.services.impact_categories import get_rule_category

    by_reg: dict[str, dict[str, object]] = {}
    counted = 0
    for f in findings:
        severity = str(f.get("severity", "")).upper()
        if severity not in _IMPACT_SEVERITIES:
            continue
        rule_id = str(f.get("rule_id", ""))
        category = get_rule_category(rule_id)
        refs = CATEGORY_REGULATION_MAP.get(category)
        if not refs:
            continue
        counted += 1
        for ref in refs:
            key = f"{ref.framework} {ref.citation}"
            entry = by_reg.setdefault(key, {
                "framework": ref.framework,
                "citation": ref.citation,
                "rationale": ref.rationale,
                "count": 0,
            })
            entry["count"] = int(entry["count"]) + 1

    ranked = dict(
        sorted(by_reg.items(), key=lambda kv: int(kv[1]["count"]), reverse=True),
    )
    return ComplianceImpact(total_findings=counted, by_regulation=ranked)


def format_compliance_impact(impact: ComplianceImpact) -> str:
    """Render a compliance-posture summary from mapped findings."""
    lines = [
        "",
        "  🛡️  CodeTrust — Compliance impact",
        "     regulations implicated by current findings",
        "",
    ]
    if not impact.by_regulation:
        lines.append("  No findings implicate mapped regulations. ✅")
        lines.append("")
        return "\n".join(lines)
    lines.append(f"  {impact.total_findings} finding(s) touch {len(impact.by_regulation)} regulation article(s):")
    lines.append("")
    for _key, e in impact.by_regulation.items():
        lines.append(f"    {e['framework']} {e['citation']:<18} {e['count']:>4} finding(s)  — {e['rationale']}")
    lines.append("")
    lines.append("  Note: surfaces regulatory exposure for review; not a legal compliance determination.")
    lines.append("")
    return "\n".join(lines)
