"""Tests for AI Model Attribution."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from src.services.ai_attribution import AIAttributor, AttributionResult


@pytest.fixture()
def attributor() -> AIAttributor:
    """Create an AIAttributor instance."""
    return AIAttributor()


class TestIDEHookAttribution:
    """Tests for IDE hook-based attribution."""

    def test_reads_attribution_jsonl(self, attributor: AIAttributor, tmp_path: Path) -> None:
        """Reads attribution from .codetrust/attribution.jsonl."""
        codetrust_dir = tmp_path / ".codetrust"
        codetrust_dir.mkdir()
        jsonl_file = codetrust_dir / "attribution.jsonl"
        jsonl_file.write_text(json.dumps({
            "timestamp": "2026-03-25T10:00:00Z",
            "provider": "anthropic",
            "model": "claude-sonnet-4-20250514",
            "active_file": "src/api.py",
            "workspace": str(tmp_path),
            "source_extension": "saoudrizwan.claude-dev",
        }) + "\n")

        filepath = tmp_path / "src" / "api.py"
        filepath.parent.mkdir(parents=True)
        filepath.write_text("x = 1\n")

        result = attributor.analyze_file(filepath, workspace=tmp_path)
        assert result.primary_source == "anthropic"
        assert result.primary_model == "claude-sonnet-4-20250514"
        assert result.method == "ide_hook"
        assert result.ai_probability > 0.9

    def test_no_attribution_file(self, attributor: AIAttributor, tmp_path: Path) -> None:
        """No attribution file returns unknown."""
        filepath = tmp_path / "test.py"
        filepath.write_text("x = 1\n")
        result = attributor.analyze_file(filepath, workspace=tmp_path)
        assert result.primary_source == "unknown"
        assert result.ai_probability == 0.0

    def test_file_not_in_attribution(self, attributor: AIAttributor, tmp_path: Path) -> None:
        """File not mentioned in attribution returns heuristic/unknown."""
        codetrust_dir = tmp_path / ".codetrust"
        codetrust_dir.mkdir()
        jsonl_file = codetrust_dir / "attribution.jsonl"
        jsonl_file.write_text(json.dumps({
            "provider": "openai", "model": "gpt-4o",
            "active_file": "other_file.py",
        }) + "\n")

        filepath = tmp_path / "test.py"
        filepath.write_text("x = 1\n")
        result = attributor.analyze_file(filepath, workspace=tmp_path)
        assert result.method != "ide_hook"


class TestHeuristicAttribution:
    """Tests for heuristic-based attribution."""

    def test_copilot_comment(self, attributor: AIAttributor, tmp_path: Path) -> None:
        """Detects '# Generated by GitHub Copilot' comment."""
        filepath = tmp_path / "test.py"
        filepath.write_text("# Generated by GitHub Copilot\nx = 1\n")
        result = attributor.analyze_file(filepath, workspace=tmp_path)
        assert result.primary_source == "github_copilot"
        assert result.ai_probability > 0.0

    def test_claude_comment(self, attributor: AIAttributor, tmp_path: Path) -> None:
        """Detects '# Generated by Claude' comment."""
        filepath = tmp_path / "test.py"
        filepath.write_text("# Generated by Claude\ndef foo(): pass\n")
        result = attributor.analyze_file(filepath, workspace=tmp_path)
        assert result.primary_source == "anthropic"

    def test_no_ai_patterns(self, attributor: AIAttributor, tmp_path: Path) -> None:
        """Clean human code returns no signals."""
        filepath = tmp_path / "test.py"
        filepath.write_text("def add(a, b):\n    return a + b\n")
        result = attributor.analyze_file(filepath, workspace=tmp_path)
        assert result.ai_probability == 0.0

    def test_chatbot_preamble(self, attributor: AIAttributor, tmp_path: Path) -> None:
        """Detects chatbot preamble patterns."""
        filepath = tmp_path / "test.py"
        filepath.write_text("# I'll create an implementation for the login flow\nx = 1\n")
        result = attributor.analyze_file(filepath, workspace=tmp_path)
        assert result.primary_source == "generic_ai"


class TestGitAttribution:
    """Tests for git trailer-based attribution."""

    def test_co_authored_by_claude(self, attributor: AIAttributor, tmp_path: Path) -> None:
        """Detects Co-Authored-By: Claude in git log (integration)."""
        # This test runs on the actual CodeTrust repo which has Claude co-author trailers
        result = attributor.analyze_file(
            Path("src/services/ast_analyzer.py"),
            workspace=Path("."),
        )
        # Should find anthropic via git trailer
        has_anthropic = any(
            s.source == "anthropic" for s in result.signals
        )
        assert has_anthropic


class TestDirectoryAnalysis:
    """Tests for directory-level analysis."""

    def test_analyze_directory(self, attributor: AIAttributor, tmp_path: Path) -> None:
        """Analyzes all matching files in directory."""
        (tmp_path / "clean.py").write_text("x = 1\n")
        (tmp_path / "ai.py").write_text("# Generated by Claude\nx = 1\n")
        (tmp_path / "readme.txt").write_text("Not scanned\n")

        results = attributor.analyze_directory(tmp_path)
        # Only ai.py should have signals
        assert len(results) >= 1
        filenames = [r.file for r in results]
        assert any("ai.py" in f for f in filenames)


class TestBuildReport:
    """Tests for report building."""

    def test_empty_results(self, attributor: AIAttributor) -> None:
        """Empty results produce clean report."""
        report = attributor.build_report([])
        assert "0 files" in report

    def test_report_with_results(self, attributor: AIAttributor) -> None:
        """Report includes file details."""
        results = [
            AttributionResult(
                file="test.py", primary_source="anthropic",
                primary_model="claude-sonnet-4-20250514",
                ai_probability=0.95, method="ide_hook",
            ),
        ]
        report = attributor.build_report(results)
        assert "anthropic" in report
        assert "test.py" in report
