{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codetrust.fullname" . }}
  labels:
    {{- include "codetrust.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.secrets.apiKey | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  github-client-id: {{ .Values.secrets.githubClientId | b64enc | quote }}
  github-client-secret: {{ .Values.secrets.githubClientSecret | b64enc | quote }}
  stripe-secret-key: {{ .Values.secrets.stripeSecretKey | b64enc | quote }}
  stripe-webhook-secret: {{ .Values.secrets.stripeWebhookSecret | b64enc | quote }}
  oidc-client-id: {{ .Values.secrets.oidcClientId | b64enc | quote }}
  oidc-client-secret: {{ .Values.secrets.oidcClientSecret | b64enc | quote }}
{{- end }}
